import "./globals.css";
import localFont from "@next/font/local";

const cera_pro = localFont({
  src: [
    {
      path: "../public/fonts/Cera Pro Light.ttf",
      weight: "700",
    },
  ],
  variable: "--font-cera-pro",
});

export const metadata = {
  title: "booksmart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${cera_pro.variable} font-sans`}>
      <body className="container mx-auto px-40 py-14">{children}</body>
    </html>
  );
}
